### ISSUE TITLE
gatotray v3.0 is at Bitbucket

### ISSUE THREAD

**Issue by gatopeich** [kafene/gatotray#3]
Hello @kafene , I resurrected gatotray to add `xscreensaver` support, which gives it new life for my everyday work experience.

Since Google code let us down, I had to restart the repo at Bitbucket since it is more handy for me: https://bitbucket.org/gatopeich/gatotray

Kind regards,
@gatopeich

**Comment by AlisterH** [comment]
Hi gatopeich, you seem to have deleted that repository. Or have you moved it somewhere else?
Thanks.

**Comment by gatopeich** [comment]
Sorry I forgot to make it public!!!
Should be visible now...

**Comment by kafene** [comment]
Thanks, I put a link to the new repo in the README so anyone who comes across this knows where to get the latest version.

**Comment by gatopeich** [comment]
That is great, thanks.
I hope you like the new features!
